# Generated by Django 4.2.3 on 2023-11-25 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_heading_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='heading',
        ),
    ]
