# Generated by Django 4.2.3 on 2023-11-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_post_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.AddField(
            model_name='post',
            name='imali',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
