# Generated by Django 4.2.7 on 2023-11-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
