# Generated by Django 5.0.1 on 2024-03-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_query_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
