# Generated by Django 4.2.7 on 2023-11-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_query_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='time',
            field=models.DateTimeField(default=934),
            preserve_default=False,
        ),
    ]
