# Generated by Django 4.2.7 on 2023-11-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_query_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='time',
            field=models.TimeField(),
        ),
    ]
