# Generated by Django 5.0.1 on 2024-03-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_chatconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='session_id',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
