# Generated by Django 4.2.3 on 2023-11-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_post_images_post_imali'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subheading',
            field=models.CharField(default=1, max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
